---
abstract: 'tiny, yet Moo(se)-compatible type constraint'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.010, CPAN::Meta::Converter version 2.120921'
keywords:
  - 'Argument Checking'
  - 'Argument Validation'
  - Moo
  - Moose
  - Mouse
  - 'Parameter Checking'
  - 'Parameter Validation'
  - Schema
  - 'Type Coercion'
  - 'Type Constraint'
  - 'Type Library'
  - Validation
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Type-Tiny
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Devel::TypeTiny::Perl56Compat:
    file: lib/Devel/TypeTiny/Perl56Compat.pm
    version: 0.027_05
  Devel::TypeTiny::Perl58Compat:
    file: lib/Devel/TypeTiny/Perl58Compat.pm
    version: 0.027_05
  Eval::TypeTiny:
    file: lib/Eval/TypeTiny.pm
    version: 0.027_05
  Exporter::TypeTiny:
    file: lib/Exporter/TypeTiny.pm
    version: 0.027_05
  Reply::Plugin::TypeTiny:
    file: lib/Reply/Plugin/TypeTiny.pm
    version: 0.027_05
  Test::TypeTiny:
    file: lib/Test/TypeTiny.pm
    version: 0.027_05
  Type::Coercion:
    file: lib/Type/Coercion.pm
    version: 0.027_05
  Type::Coercion::Union:
    file: lib/Type/Coercion/Union.pm
    version: 0.027_05
  Type::Exception:
    file: lib/Type/Exception.pm
    version: 0.027_05
  Type::Exception::Assertion:
    file: lib/Type/Exception/Assertion.pm
    version: 0.027_05
  Type::Exception::Compilation:
    file: lib/Type/Exception/Compilation.pm
    version: 0.027_05
  Type::Exception::WrongNumberOfParameters:
    file: lib/Type/Exception/WrongNumberOfParameters.pm
    version: 0.027_05
  Type::Library:
    file: lib/Type/Library.pm
    version: 0.027_05
  Type::Params:
    file: lib/Type/Params.pm
    version: 0.027_05
  Type::Parser:
    file: lib/Type/Parser.pm
    version: 0.027_05
  Type::Registry:
    file: lib/Type/Registry.pm
    version: 0.027_05
  Type::Tiny:
    file: lib/Type/Tiny.pm
    version: 0.027_05
  Type::Tiny::Class:
    file: lib/Type/Tiny/Class.pm
    version: 0.027_05
  Type::Tiny::Duck:
    file: lib/Type/Tiny/Duck.pm
    version: 0.027_05
  Type::Tiny::Enum:
    file: lib/Type/Tiny/Enum.pm
    version: 0.027_05
  Type::Tiny::Intersection:
    file: lib/Type/Tiny/Intersection.pm
    version: 0.027_05
  Type::Tiny::Role:
    file: lib/Type/Tiny/Role.pm
    version: 0.027_05
  Type::Tiny::Union:
    file: lib/Type/Tiny/Union.pm
    version: 0.027_05
  Type::Utils:
    file: lib/Type/Utils.pm
    version: 0.027_05
  Types::Standard:
    file: lib/Types/Standard.pm
    version: 0.027_05
  Types::TypeTiny:
    file: lib/Types/TypeTiny.pm
    version: 0.027_05
recommends:
  Devel::LexAlias: 0.05
  Devel::StackTrace: 0
  Type::Tie: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Type-Tiny/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Tiny
  homepage: https://metacpan.org/release/Type-Tiny
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-type-tiny
version: 0.027_05
x_contributors:
  - 'Diab Jerius (DJERIUS) <djerius@cpan.org>'
  - 'Vyacheslav Matyukhin (MMCLERIC) <mmcleric@cpan.org>'
  - 'Pierre Masci'
  - 'Mark Stosberg (MARKSTOS) <markstos@cpan.org>'
