---
abstract: 'tiny, yet Moo(se)-compatible type constraint'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - 'Argument Checking'
  - 'Argument Validation'
  - Moo
  - Moose
  - Mouse
  - 'Parameter Checking'
  - 'Parameter Validation'
  - Schema
  - 'Type Coercion'
  - 'Type Constraint'
  - 'Type Library'
  - Validation
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Type::Tiny
name: Type-Tiny
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  Devel::StackTrace: 0
  Type::Tie: 0
requires:
  perl: 5.6.1
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Tiny
  homepage: https://metacpan.org/release/Type-Tiny
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-type-tiny
version: 0.018
x_contributors:
  - 'Mark Stosberg <markstos@cpan.org>'
  - 'Diab Jerius <djerius@cpan.org>'
  - 'Vyacheslav Matyukhin <mmcleric@cpan.org>'
  - 'Pierre Masci'
